"""Add song_id to Lesson

Revision ID: 0c0da9d8e453
Revises: 
Create Date: 2025-06-25 13:53:55.034852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c0da9d8e453'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('song_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'song', ['song_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('song_id')

    # ### end Alembic commands ###
